# Generated by Django 6.1.1 on 2026-09-24 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_timetableslot_secondary_teacher'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='sent at')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reminder', to='academics.lesson', verbose_name='lesson')),
            ],
            options={
                'verbose_name': 'unmarked attendance reminder',
                'verbose_name_plural': 'unmarked attendance reminders',
            },
        ),
    ]
