# Generated by Django 6.1.1 on 2026-09-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancereminder'),
        ('organizations', '0002_default_school_and_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='attendancereminder',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reminders', to='organizations.organization', verbose_name='organization'),
        ),
    ]
