# Generated by Django 6.1.1 on 2026-09-27 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_default_school_and_memberships'),
        ('schools', '0002_schoolclass_total_xp'),
        ('users', '0008_backfill_user_active_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AddConstraint(
            model_name='schoolclass',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_class_name_per_organization'),
        ),
    ]
