# Generated by Django 6.1.1 on 2026-09-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_category'),
        ('organizations', '0002_default_school_and_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Which organization raised this notification. Required for anything generated inside one; NULL is reserved for platform-level messages.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organizations.organization', verbose_name='organization'),
        ),
    ]
