# Generated by Django 6.1.1 on 2026-10-03 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('endpoint', models.URLField(max_length=500, unique=True, verbose_name='endpoint')),
                ('p256dh', models.CharField(max_length=200, verbose_name='p256dh key')),
                ('auth', models.CharField(max_length=100, verbose_name='auth secret')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'push subscription',
                'verbose_name_plural': 'push subscriptions',
                'ordering': ('-created_at',),
            },
        ),
    ]
