# Generated by Django 6.1.1 on 2026-09-27 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_default_school_and_memberships'),
        ('users', '0006_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_organization',
            field=models.ForeignKey(blank=True, help_text='Which organization this user is currently working in. NULL means the user has no membership yet and the platform falls back to their only membership, or to no organization at all.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='organizations.organization', verbose_name='active organization'),
        ),
    ]
