# Generated by Django 6.1.1 on 2026-10-04 16:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_backfill_user_active_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='middle name'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='passport number'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pinfl',
            field=models.CharField(blank=True, help_text='Jismoniy shaxsning identifikatsiya raqami (14 raqam).', max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', "PINFL 14 ta raqamdan iborat bo'lishi kerak.")], verbose_name='PINFL'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='region',
            field=models.CharField(blank=True, max_length=120, verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('director', 'Director'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=20, verbose_name='role'),
        ),
    ]
