# Generated by Django 6.1.1 on 2026-10-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_lowercase_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='handle',
            field=models.SlugField(blank=True, help_text="Ommaviy profil manzili: /p/<handle>/. Bo'sh bo'lsa profil ochilmaydi.", max_length=30, null=True, unique=True, verbose_name='handle'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_profile_public',
            field=models.BooleanField(default=False, help_text="Yoqilsa, handle orqali profil hamma uchun ochiq bo'ladi.", verbose_name='public profile'),
        ),
    ]
