# Generated by Django 6.1.1 on 2026-10-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_handle_user_is_profile_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='osid',
            field=models.CharField(blank=True, help_text="10 xonali barqaror identifikator. Tashqi tizimlar (yuz terminali, uzedu) odamni shu kalit orqali bog'laydi. Avtomatik beriladi.", max_length=10, null=True, unique=True, verbose_name='OSID'),
        ),
    ]
