# Generated by Django 6.1.1 on 2026-09-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_activity_activitysubmission_activityresult_and_more'),
        ('organizations', '0002_default_school_and_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='activityresult',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_results', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_submissions', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='test',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='organizations.organization', verbose_name='organization'),
        ),
    ]
