# Generated by Django 6.1.1 on 2026-10-04 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0010_merge_20260929_1532'),
        ('organizations', '0002_default_school_and_memberships'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file', models.FileField(blank=True, upload_to='materials/%Y/%m/', verbose_name='file')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='link')),
                ('kind', models.CharField(choices=[('LINK', 'Link'), ('PDF', 'PDF'), ('DOC', 'Document'), ('SHEET', 'Spreadsheet'), ('SLIDES', 'Presentation'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('ARCHIVE', 'Archive'), ('OTHER', 'Other')], default='OTHER', max_length=10, verbose_name='kind')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='organizations.organization', verbose_name='organization')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='academics.subject', verbose_name='subject')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materials',
                'ordering': ('-created_at',),
            },
        ),
    ]
