# Generated by Django 6.1.1 on 2026-10-09 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_default_school_and_memberships'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('token_hash', models.CharField(blank=True, max_length=255, verbose_name='token hash')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='last seen at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_bridges', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'device bridge',
                'verbose_name_plural': 'device bridges',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('vendor', models.CharField(blank=True, max_length=50, verbose_name='vendor')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='model')),
                ('serial', models.CharField(max_length=120, verbose_name='serial')),
                ('last_known_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='last known IP')),
                ('location_label', models.CharField(blank=True, max_length=120, verbose_name='location')),
                ('direction', models.CharField(choices=[('IN', 'Entry'), ('OUT', 'Exit'), ('BOTH', 'Both')], default='BOTH', max_length=4, verbose_name='direction')),
                ('capabilities', models.JSONField(blank=True, default=dict, verbose_name='capabilities')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.bridge', verbose_name='bridge')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
                'constraints': [models.UniqueConstraint(fields=('organization', 'serial'), name='unique_device_serial_per_org')],
            },
        ),
    ]
