# Generated by Django 6.1.1 on 2026-10-09 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('organizations', '0002_default_school_and_memberships'),
        ('users', '0013_backfill_osid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('raw_osid', models.CharField(max_length=64, verbose_name='raw OSID')),
                ('event_time', models.DateTimeField(verbose_name='event time')),
                ('direction', models.CharField(choices=[('IN', 'Entry'), ('OUT', 'Exit'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=8, verbose_name='direction')),
                ('verify_mode', models.CharField(blank=True, max_length=32, verbose_name='verify mode')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='raw payload')),
                ('dedup_key', models.CharField(max_length=255, unique=True, verbose_name='dedup key')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_events', to='devices.device', verbose_name='device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_events', to='organizations.organization', verbose_name='organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'access event',
                'verbose_name_plural': 'access events',
                'ordering': ['-event_time'],
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(verbose_name='date')),
                ('first_in_at', models.DateTimeField(blank=True, null=True, verbose_name='first entry')),
                ('last_out_at', models.DateTimeField(blank=True, null=True, verbose_name='last exit')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent')], default='ABSENT', max_length=10, verbose_name='status')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance', to='organizations.organization', verbose_name='organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance', to='users.studentprofile', verbose_name='student')),
            ],
            options={
                'verbose_name': 'daily attendance',
                'verbose_name_plural': 'daily attendance',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='unique_daily_attendance_per_student')],
            },
        ),
    ]
