# Generated by Django 6.1.1 on 2026-09-19 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_user_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('category', models.CharField(choices=[('ADMINISTRATIVE', "Ma'muriy"), ('REPORT', 'Hisobot'), ('MEETING', "Yig'ilish"), ('OTHER', 'Boshqa')], default='OTHER', max_length=20, verbose_name='category')),
                ('is_broadcast', models.BooleanField(default=False, verbose_name='sent to all teachers')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'teacher task',
                'verbose_name_plural': 'teacher tasks',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TeacherTaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_done', models.BooleanField(default=False, verbose_name='done')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.teachertask', verbose_name='task')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='users.teacherprofile', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'teacher task assignment',
                'verbose_name_plural': 'teacher task assignments',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('task', 'teacher'), name='unique_teacher_task_assignment')],
            },
        ),
    ]
