# Generated by Django 6.1.1 on 2026-09-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_default_school_and_memberships'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertask',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_tasks', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='teachertaskassignment',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_task_assignments', to='organizations.organization', verbose_name='organization'),
        ),
    ]
