# Generated by Django 6.1.1 on 2026-09-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_default_school_and_memberships'),
        ('school_config', '0002_schooltimesettings_long_break_after_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltimesettings',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_settings', to='organizations.organization', verbose_name='organization'),
        ),
    ]
