# Generated by Django 6.1.1 on 2026-09-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_config', '0002_schooltimesettings_long_break_after_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltimesettings',
            name='second_short_period',
            field=models.PositiveSmallIntegerField(default=4, help_text='Which period of the second shift is shorter than the standard duration.', verbose_name='second shift short period'),
        ),
        migrations.AddField(
            model_name='schooltimesettings',
            name='second_short_period_minutes',
            field=models.PositiveSmallIntegerField(default=35, verbose_name='second shift short period (minutes)'),
        ),
        migrations.AddField(
            model_name='schooltimesettings',
            name='second_start_time',
            field=models.TimeField(blank=True, help_text='Leave empty when the school runs a single shift.', null=True, verbose_name='second shift start time'),
        ),
    ]
