# Generated by Django 6.1.1 on 2026-09-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_config', '0003_schooltimesettings_second_shift'),
        ('school_config', '0004_alter_schooltimesettings_organization'),
    ]

    operations = [
    ]
