# Generated by Django 6.1.1 on 2026-10-04 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_config', '0005_merge_20260929_1532'),
        ('schools', '0005_schoolclass_organization_not_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAccessWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_access_windows', to=settings.AUTH_USER_MODEL, verbose_name='opened by')),
                ('school_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_window', to='schools.schoolclass', verbose_name='class')),
            ],
            options={
                'verbose_name': 'class access window',
                'verbose_name_plural': 'class access windows',
                'ordering': ('-expires_at',),
            },
        ),
    ]
