# Generated by Django 6.1.1 on 2026-10-04 08:08

import apps.school_config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_config', '0006_classaccesswindow'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltimesettings',
            name='school_days',
            field=models.JSONField(default=apps.school_config.models.default_school_days, help_text='ISO weekdays the lock is active on (1=Mon … 7=Sun). Default is Mon–Sat, so Sunday is open.', verbose_name='school days'),
        ),
    ]
