# Generated by Django 6.1.1 on 2026-10-04 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_default_school_and_memberships'),
        ('school_config', '0007_schooltimesettings_school_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDayException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('kind', models.CharField(choices=[('OFF', 'Day off'), ('SCHOOL', 'School day')], default='OFF', max_length=6, verbose_name='kind')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_exceptions', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'school day exception',
                'verbose_name_plural': 'school day exceptions',
                'ordering': ('-start_date',),
            },
        ),
    ]
