# Generated by Django 6.1.1 on 2026-09-24 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_lessonreminder'),
        ('users', '0006_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableslot',
            name='secondary_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_timetable_slots', to='users.teacherprofile', verbose_name='secondary teacher'),
        ),
    ]
