# Generated by Django 6.1.1 on 2026-09-27 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_timetableslot_secondary_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyScheduleDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(verbose_name='date')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='sent at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedule_digests', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'daily schedule digest',
                'verbose_name_plural': 'daily schedule digests',
                'ordering': ('-date',),
            },
        ),
        migrations.DeleteModel(
            name='LessonReminder',
        ),
        migrations.AddConstraint(
            model_name='dailyscheduledigest',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_schedule_per_user'),
        ),
    ]
