# Generated by Django 6.1.1 on 2026-09-27 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_dailyscheduledigest_delete_lessonreminder_and_more'),
        ('organizations', '0002_default_school_and_memberships'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailyscheduledigest',
            name='unique_daily_schedule_per_user',
        ),
        migrations.AddField(
            model_name='dailyscheduledigest',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedule_digests', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddConstraint(
            model_name='dailyscheduledigest',
            constraint=models.UniqueConstraint(fields=('user', 'organization', 'date'), name='unique_daily_schedule_per_user_org'),
        ),
    ]
