# Generated by Django 6.1.1 on 2026-09-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_timetableslot_times'),
        ('academics', '0009_alter_dailyscheduledigest_organization_and_more'),
    ]

    operations = [
    ]
