# Generated by Django 6.1.1 on 2026-10-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=120, verbose_name='ism')),
                ('phone', models.CharField(max_length=32, verbose_name='telefon')),
                ('school_name', models.CharField(blank=True, max_length=200, verbose_name='maktab nomi')),
                ('message', models.TextField(blank=True, verbose_name='xabar')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('contacted', "Bog'lanildi"), ('closed', 'Yopildi')], default='new', max_length=16, verbose_name='holat')),
            ],
            options={
                'verbose_name': "demo so'rovi",
                'verbose_name_plural': "demo so'rovlari",
                'ordering': ('-created_at',),
            },
        ),
    ]
