# Generated by Django 6.1.1 on 2026-09-19 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
        ('users', '0006_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentLinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='code')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='used at')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_link_codes', to='users.studentprofile', verbose_name='student')),
            ],
            options={
                'verbose_name': 'parent link code',
                'verbose_name_plural': 'parent link codes',
            },
        ),
        migrations.CreateModel(
            name='ParentTelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('telegram_id', models.BigIntegerField(verbose_name='telegram chat id')),
                ('telegram_username', models.CharField(blank=True, max_length=150, verbose_name='telegram username')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_telegram_accounts', to='users.studentprofile', verbose_name='student')),
            ],
            options={
                'verbose_name': 'parent telegram account',
                'verbose_name_plural': 'parent telegram accounts',
                'constraints': [models.UniqueConstraint(fields=('student', 'telegram_id'), name='unique_parent_telegram_link')],
            },
        ),
    ]
