# Generated by Django 6.1.1 on 2026-09-19 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_lessonreminder'),
        ('users', '0006_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('game_type', models.CharField(choices=[('TUG_OF_WAR', 'Arqon tortish'), ('QUIZ', 'Viktorina')], max_length=20, verbose_name='game type')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('questions', models.JSONField(blank=True, default=list, verbose_name='questions')),
                ('score_percent', models.FloatField(blank=True, null=True, verbose_name='score (%)')),
                ('xp_awarded', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='XP awarded')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='users.studentprofile', verbose_name='student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.subject', verbose_name='subject')),
            ],
            options={
                'verbose_name': 'game session',
                'verbose_name_plural': 'game sessions',
                'ordering': ('-created_at',),
            },
        ),
    ]
