# Generated by Django 6.1.1 on 2026-09-20 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_lessonreminder'),
        ('games', '0001_initial'),
        ('schools', '0002_schoolclass_total_xp'),
        ('users', '0006_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PooledQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('text', models.TextField(verbose_name='question text')),
                ('options', models.JSONField(verbose_name='options')),
                ('correct_index', models.PositiveSmallIntegerField(verbose_name='correct option index')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.schoolclass', verbose_name='class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.subject', verbose_name='subject')),
            ],
            options={
                'verbose_name': 'pooled question',
                'verbose_name_plural': 'pooled questions',
            },
        ),
        migrations.CreateModel(
            name='PooledQuestionServed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('served_at', models.DateTimeField(auto_now_add=True, verbose_name='served at')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.pooledquestion', verbose_name='question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.studentprofile', verbose_name='student')),
            ],
            options={
                'verbose_name': 'served pooled question',
                'verbose_name_plural': 'served pooled questions',
            },
        ),
        migrations.AddIndex(
            model_name='pooledquestion',
            index=models.Index(fields=['subject', 'school_class'], name='games_poole_subject_b3c264_idx'),
        ),
        migrations.AddConstraint(
            model_name='pooledquestionserved',
            constraint=models.UniqueConstraint(fields=('student', 'question'), name='unique_student_pooled_question'),
        ),
    ]
