# Generated by Django 6.1.1 on 2026-09-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_pooledquestion_pooledquestionserved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='answers',
            field=models.JSONField(blank=True, default=dict, verbose_name='answers'),
        ),
        migrations.AddField(
            model_name='pooledquestion',
            name='explanation',
            field=models.TextField(blank=True, default='', verbose_name='explanation'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('TUG_OF_WAR', 'Arqon tortish'), ('QUIZ', 'Viktorina'), ('TOWER_BUILDER', 'Minora qurish')], max_length=20, verbose_name='game type'),
        ),
    ]
