# Generated by Django 6.1.1 on 2026-09-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_tower_builder'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='secret_code',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='secret code'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('TUG_OF_WAR', 'Arqon tortish'), ('QUIZ', 'Viktorina'), ('TOWER_BUILDER', 'Minora qurish'), ('CODE_BREAKER', 'Kodni buzish')], max_length=20, verbose_name='game type'),
        ),
    ]
