# Generated by Django 6.1.1 on 2026-09-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_treasure_hunt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('TUG_OF_WAR', 'Arqon tortish'), ('QUIZ', 'Viktorina'), ('TOWER_BUILDER', 'Minora qurish'), ('CODE_BREAKER', 'Kodni buzish'), ('TREASURE_HUNT', 'Xazina ovi'), ('BATTLE_ARENA', 'Jang maydoni')], max_length=20, verbose_name='game type'),
        ),
    ]
