# Generated by Django 6.1.1 on 2026-09-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_battle_arena'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('EASY', 'Oson'), ('MEDIUM', "O'rta"), ('HARD', 'Qiyin')], default='', max_length=10, verbose_name='difficulty'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('TUG_OF_WAR', 'Arqon tortish'), ('QUIZ', 'Viktorina'), ('TOWER_BUILDER', 'Minora qurish'), ('CODE_BREAKER', 'Kodni buzish'), ('TREASURE_HUNT', 'Xazina ovi'), ('BATTLE_ARENA', 'Jang maydoni'), ('TOWER_DEFENSE', 'Tower Defense')], max_length=20, verbose_name='game type'),
        ),
    ]
