# Generated by Django 6.1.1 on 2026-09-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_tower_defense'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='nitro_rounds',
            field=models.JSONField(blank=True, default=list, verbose_name='nitro rounds'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('TUG_OF_WAR', 'Arqon tortish'), ('QUIZ', 'Viktorina'), ('TOWER_BUILDER', 'Minora qurish'), ('CODE_BREAKER', 'Kodni buzish'), ('TREASURE_HUNT', 'Xazina ovi'), ('BATTLE_ARENA', 'Jang maydoni'), ('TOWER_DEFENSE', 'Tower Defense'), ('NEON_RACING', 'Neon Racing')], max_length=20, verbose_name='game type'),
        ),
    ]
