# Generated by Django 6.1.1 on 2026-09-27 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_timetableslot_secondary_teacher'),
        ('games', '0008_neon_racing'),
        ('schools', '0002_schoolclass_total_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pooledquestion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='pooledquestion',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pooled_questions', to='schools.schoolclass', verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='pooledquestion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pooled_questions', to='academics.subject', verbose_name='subject'),
        ),
        migrations.AddIndex(
            model_name='pooledquestion',
            index=models.Index(fields=['subject', 'is_active'], name='games_poole_subject_cc1dc5_idx'),
        ),
    ]
