# Generated by Django 6.1.1 on 2026-09-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_pooledquestion_is_active_and_more'),
        ('organizations', '0002_default_school_and_memberships'),
        ('users', '0008_backfill_user_active_organization'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pooledquestionserved',
            name='unique_student_pooled_question',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='pooledquestion',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pooled_questions', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='pooledquestionserved',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='served_pooled_questions', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddConstraint(
            model_name='pooledquestionserved',
            constraint=models.UniqueConstraint(fields=('organization', 'student', 'question'), name='unique_student_pooled_question_per_org'),
        ),
    ]
