# Generated by Django 6.1.1 on 2026-09-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_achievement_icon_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xptransaction',
            name='source',
            field=models.CharField(choices=[('TEST', 'Test'), ('ACTIVITY', 'Activity'), ('DUEL', 'Duel')], max_length=20, verbose_name='source'),
        ),
    ]
