# Generated by Django 6.1.1 on 2026-09-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_alter_xptransaction_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xptransaction',
            name='source',
            field=models.CharField(choices=[('TEST', 'Test'), ('ACTIVITY', 'Activity'), ('DUEL', 'Duel'), ('REMEDIAL_GAME', 'Remedial game')], max_length=20, verbose_name='source'),
        ),
    ]
