# Generated by Django 6.1.1 on 2026-09-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_alter_xptransaction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='xp_reward',
            field=models.PositiveIntegerField(default=0, help_text='Awarded once, the moment a student unlocks this achievement.', verbose_name='XP reward'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='condition_type',
            field=models.CharField(choices=[('FIRST_TEST', 'Complete your first test'), ('TEST_COUNT', 'Complete N tests'), ('PERFECT_SCORE', 'Score 100% on a test'), ('XP_THRESHOLD', 'Reach a total XP threshold'), ('STREAK_LENGTH', 'Reach a streak length')], max_length=20, verbose_name='condition type'),
        ),
        migrations.AlterField(
            model_name='xptransaction',
            name='source',
            field=models.CharField(choices=[('TEST', 'Test'), ('ACTIVITY', 'Activity'), ('DUEL', 'Duel'), ('REMEDIAL_GAME', 'Remedial game'), ('GAME', 'Practice game'), ('ACHIEVEMENT', 'Achievement unlocked')], max_length=20, verbose_name='source'),
        ),
    ]
