# Generated by Django 6.1.1 on 2026-09-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_achievement_xp_reward_and_more'),
        ('organizations', '0002_default_school_and_memberships'),
        ('users', '0008_backfill_user_active_organization'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentachievement',
            name='unique_student_achievement',
        ),
        migrations.AddField(
            model_name='streak',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='studentachievement',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_achievements', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='xptransaction',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='streak',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='users.studentprofile', verbose_name='student'),
        ),
        migrations.AddConstraint(
            model_name='streak',
            constraint=models.UniqueConstraint(fields=('organization', 'student'), name='unique_streak_per_student_org'),
        ),
        migrations.AddConstraint(
            model_name='studentachievement',
            constraint=models.UniqueConstraint(fields=('organization', 'student', 'achievement'), name='unique_student_achievement_per_org'),
        ),
    ]
