# Generated by Django 6.1.1 on 2026-10-04 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0010_alter_streak_organization_and_more'),
        ('organizations', '0002_default_school_and_memberships'),
        ('users', '0008_backfill_user_active_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('week_start', models.DateField(verbose_name='processed week (Monday)')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_cycles', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'league cycle',
                'verbose_name_plural': 'league cycles',
                'ordering': ('-week_start',),
                'constraints': [models.UniqueConstraint(fields=('organization', 'week_start'), name='unique_league_cycle_per_org_week')],
            },
        ),
        migrations.CreateModel(
            name='LeagueStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('tier', models.PositiveSmallIntegerField(default=1, verbose_name='tier')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_standings', to='organizations.organization', verbose_name='organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_standings', to='users.studentprofile', verbose_name='student')),
            ],
            options={
                'verbose_name': 'league standing',
                'verbose_name_plural': 'league standings',
                'ordering': ('-tier',),
                'constraints': [models.UniqueConstraint(fields=('organization', 'student'), name='unique_league_standing_per_org')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('target_xp', models.PositiveIntegerField(default=500, verbose_name='weekly XP target')),
                ('goal_streak', models.PositiveIntegerField(default=0, verbose_name='weeks hit in a row')),
                ('best_goal_streak', models.PositiveIntegerField(default=0, verbose_name='best weekly streak')),
                ('last_completed_week', models.DateField(blank=True, null=True, verbose_name='last completed week')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_goals', to='organizations.organization', verbose_name='organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_goals', to='users.studentprofile', verbose_name='student')),
            ],
            options={
                'verbose_name': 'weekly goal',
                'verbose_name_plural': 'weekly goals',
                'constraints': [models.UniqueConstraint(fields=('organization', 'student'), name='unique_weekly_goal_per_org')],
            },
        ),
    ]
