# Generated by Django 6.1.1 on 2026-09-19 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_lessonreminder'),
        ('learning', '0002_activity_activitysubmission_activityresult_and_more'),
        ('users', '0006_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemedialSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXPLAINED', 'Explained'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20, verbose_name='status')),
                ('explanation', models.TextField(blank=True, verbose_name='AI explanation')),
                ('questions', models.JSONField(blank=True, default=list, verbose_name='game questions')),
                ('score_percent', models.FloatField(blank=True, null=True, verbose_name='game score (%)')),
                ('xp_awarded', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='XP awarded')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remedial_sessions', to='learning.testattempt', verbose_name='test attempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remedial_sessions', to='users.studentprofile', verbose_name='student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.subject', verbose_name='subject')),
            ],
            options={
                'verbose_name': 'remedial session',
                'verbose_name_plural': 'remedial sessions',
                'ordering': ('-created_at',),
            },
        ),
    ]
