# Generated by Django 6.1.1 on 2026-09-23 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_lessonreminder'),
        ('games', '0006_battle_arena'),
        ('learning', '0002_activity_activitysubmission_activityresult_and_more'),
        ('remedial', '0001_initial'),
        ('users', '0006_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedialsession',
            name='game_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remedial_sessions', to='games.gamesession', verbose_name='game session'),
        ),
        migrations.AlterField(
            model_name='remedialsession',
            name='attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remedial_sessions', to='learning.testattempt', verbose_name='test attempt'),
        ),
        migrations.AddConstraint(
            model_name='remedialsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('attempt__isnull', False), ('game_session__isnull', True)), models.Q(('attempt__isnull', True), ('game_session__isnull', False)), _connector='OR'), name='remedial_exactly_one_source'),
        ),
        migrations.AddConstraint(
            model_name='remedialsession',
            constraint=models.UniqueConstraint(condition=models.Q(('game_session__isnull', False)), fields=('game_session',), name='unique_remedial_per_game_session'),
        ),
    ]
