# Generated by Django 6.1.1 on 2026-09-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_default_school_and_memberships'),
        ('remedial', '0002_game_remedial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedialsession',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remedial_sessions', to='organizations.organization', verbose_name='organization'),
        ),
    ]
