# Generated by Django 6.1.1 on 2026-09-27 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('type', models.CharField(choices=[('SCHOOL', 'School'), ('CLUB', 'Club'), ('COURSE', 'Course')], default='SCHOOL', max_length=10, verbose_name='type')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='slug')),
                ('timezone', models.CharField(default='Asia/Tashkent', help_text="IANA name. Drives this organization's clock and notifications.", max_length=64, verbose_name='timezone')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive organizations keep their data but nobody can sign in to them.', verbose_name='is active')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ('type', 'name'),
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Administrator'), ('DIRECTOR', 'Director'), ('TEACHER', 'Teacher'), ('COACH', 'Coach'), ('STUDENT', 'Student'), ('MEMBER', 'Member')], max_length=20, verbose_name='role')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INVITED', 'Invited'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=10, verbose_name='status')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='joined at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization', verbose_name='organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'organization membership',
                'verbose_name_plural': 'organization memberships',
                'ordering': ('organization__type', 'organization__name', 'role', 'user__email'),
                'indexes': [models.Index(fields=['organization', 'role'], name='org_membership_role_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'organization'), name='unique_user_organization_membership')],
            },
        ),
    ]
