# Generated by Django 6.1.1 on 2026-10-09 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_default_school_and_memberships'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('denied', models.JSONField(blank=True, default=list, help_text='Taqiqlangan imkoniyatlar, masalan: materials.read, students.create', verbose_name='denied capabilities')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_config', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'client config',
                'verbose_name_plural': 'client configs',
            },
        ),
    ]
