# Generated by Django 6.1.1 on 2026-09-19 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0002_activity_activitysubmission_activityresult_and_more'),
        ('schools', '0002_schoolclass_total_xp'),
        ('users', '0006_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('result', models.CharField(blank=True, choices=[('CHALLENGER', 'Challenger won'), ('OPPONENT', 'Opponent won'), ('DRAW', 'Draw')], max_length=20, null=True, verbose_name='result')),
                ('challenger_started_at', models.DateTimeField(blank=True, null=True, verbose_name='challenger started at')),
                ('challenger_submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='challenger submitted at')),
                ('challenger_score_percent', models.FloatField(blank=True, null=True, verbose_name='challenger score (%)')),
                ('opponent_started_at', models.DateTimeField(blank=True, null=True, verbose_name='opponent started at')),
                ('opponent_submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='opponent submitted at')),
                ('opponent_score_percent', models.FloatField(blank=True, null=True, verbose_name='opponent score (%)')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_as_challenger', to='users.studentprofile', verbose_name='challenger')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_as_opponent', to='users.studentprofile', verbose_name='opponent')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels', to='schools.schoolclass', verbose_name='class')),
            ],
            options={
                'verbose_name': 'duel',
                'verbose_name_plural': 'duels',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DuelRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('rating', models.PositiveIntegerField(default=1200, verbose_name='rating')),
                ('wins', models.PositiveIntegerField(default=0, verbose_name='wins')),
                ('losses', models.PositiveIntegerField(default=0, verbose_name='losses')),
                ('draws', models.PositiveIntegerField(default=0, verbose_name='draws')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duel_rating', to='users.studentprofile', verbose_name='student')),
            ],
            options={
                'verbose_name': 'duel rating',
                'verbose_name_plural': 'duel ratings',
                'ordering': ('-rating',),
            },
        ),
        migrations.CreateModel(
            name='DuelAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_correct', models.BooleanField(default=False, verbose_name='is correct')),
                ('duel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='duels.duel', verbose_name='duel')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duel_answers', to='users.studentprofile', verbose_name='participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='learning.question', verbose_name='question')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='learning.option', verbose_name='selected option')),
            ],
            options={
                'verbose_name': 'duel answer',
                'verbose_name_plural': 'duel answers',
                'constraints': [models.UniqueConstraint(fields=('duel', 'participant', 'question'), name='unique_duel_participant_answer')],
            },
        ),
        migrations.CreateModel(
            name='DuelQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('duel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duel_questions', to='duels.duel', verbose_name='duel')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='learning.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'duel question',
                'verbose_name_plural': 'duel questions',
                'ordering': ('order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('duel', 'question'), name='unique_duel_question')],
            },
        ),
    ]
