# Generated by Django 6.1.1 on 2026-09-24 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_timetableslot_secondary_teacher'),
        ('duels', '0002_alter_duelrating_rating_default'),
        ('users', '0006_user_avatar'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='duelanswer',
            name='unique_duel_participant_answer',
        ),
        migrations.RemoveConstraint(
            model_name='duelquestion',
            name='unique_duel_question',
        ),
        migrations.RemoveField(
            model_name='duel',
            name='challenger_started_at',
        ),
        migrations.RemoveField(
            model_name='duel',
            name='opponent_started_at',
        ),
        migrations.AddField(
            model_name='duel',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='accepted at'),
        ),
        migrations.AddField(
            model_name='duel',
            name='ai_level',
            field=models.CharField(blank=True, choices=[('NOVICE', 'AI Novice'), ('SCHOLAR', 'AI Scholar'), ('MASTER', 'AI Master')], default='', max_length=10, verbose_name='AI level'),
        ),
        migrations.AddField(
            model_name='duel',
            name='challenger_log',
            field=models.JSONField(blank=True, default=dict, verbose_name='challenger log'),
        ),
        migrations.AddField(
            model_name='duel',
            name='challenger_ready_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='challenger ready at'),
        ),
        migrations.AddField(
            model_name='duel',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Oson'), ('MEDIUM', "O'rta"), ('HARD', 'Qiyin')], default='MEDIUM', max_length=10, verbose_name='difficulty'),
        ),
        migrations.AddField(
            model_name='duel',
            name='match_starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='match starts at'),
        ),
        migrations.AddField(
            model_name='duel',
            name='mode',
            field=models.CharField(choices=[('CLASSMATE', 'Classmate'), ('AI', 'AI opponent')], default='CLASSMATE', max_length=12, verbose_name='mode'),
        ),
        migrations.AddField(
            model_name='duel',
            name='opponent_log',
            field=models.JSONField(blank=True, default=dict, verbose_name='opponent log'),
        ),
        migrations.AddField(
            model_name='duel',
            name='opponent_ready_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='opponent ready at'),
        ),
        migrations.AddField(
            model_name='duel',
            name='question_count',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='question count'),
        ),
        migrations.AddField(
            model_name='duel',
            name='questions',
            field=models.JSONField(blank=True, default=list, verbose_name='questions'),
        ),
        migrations.AddField(
            model_name='duel',
            name='rematch_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='duels.duel', verbose_name='rematch of'),
        ),
        migrations.AddField(
            model_name='duel',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.subject', verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='challenger_score_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='challenger accuracy (%)'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='challenger_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='challenger finished at'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duels_as_opponent', to='users.studentprofile', verbose_name='opponent'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='opponent_score_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='opponent accuracy (%)'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='opponent_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='opponent finished at'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Waiting for the opponent to accept'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20, verbose_name='status'),
        ),
        migrations.RemoveField(
            model_name='duelquestion',
            name='duel',
        ),
        migrations.RemoveField(
            model_name='duelquestion',
            name='question',
        ),
        migrations.DeleteModel(
            name='DuelAnswer',
        ),
        migrations.DeleteModel(
            name='DuelQuestion',
        ),
    ]
