# Generated by Django 6.1.1 on 2026-09-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duels', '0003_remove_duelanswer_unique_duel_participant_answer_and_more'),
        ('organizations', '0002_default_school_and_memberships'),
        ('users', '0008_backfill_user_active_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duels', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='duelrating',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duel_ratings', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='duelrating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duel_ratings', to='users.studentprofile', verbose_name='student'),
        ),
        migrations.AddConstraint(
            model_name='duelrating',
            constraint=models.UniqueConstraint(fields=('organization', 'student'), name='unique_duel_rating_per_student_org'),
        ),
    ]
